### ISSUE TITLE
standalone: true doesn't work

### ISSUE THREAD

**Issue by ulitiy** [jmreidy/grunt-browserify#114]
throws Fatal error: Object true has no method 'toLowerCase'

```
    browserify:
      all:
        options:
          standalone: true
        files:
          'js/<%= pkg.name %>.browser.js': 'js/<%= pkg.name %>.js'
```
